[package]
name = "falconasm"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = { version = "0.28", features = ["all-widgets"] }
crossterm = "0.29"
rfd = "0.15"
arboard = "3"
thiserror = "1"

[profile.release]
opt-level = 3        # máxima optmizing
lto = "fat"          # complete LTO  
codegen-units = 1    # better perform
panic = "abort"      # less overhead
debug = false
incremental = false
