[package]
name = "falconasm"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = { version = "0.28", features = ["all-widgets"] }
crossterm = "0.29"
rfd = "0.15"

[profile.release]
opt-level = 3        # máxima otimização de código
lto = "fat"          # LTO completo 
codegen-units = 1    # força compilação monolítica (melhor perf)
panic = "abort"      # remove desempacotamento; reduz overhead
debug = false
incremental = false
